### ISSUE TITLE
Configuration dialog: load existing configuration

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/shpsync#3]
When the configuration dialog is opened on an aldreay configured project, defaults are loaded instead of the current project configuration.

**Comment by carolinux** [comment]
I did not initially mean for the configuration to be editable in the first place. I assumed that when somebody wants to do a different config, they will create a new project and start from scratch. If we allow editing the configuration, we need to also think about re-populating the existing excel rows with the new qgsexpressions.

**Comment by m-kuhn** [comment]
At the moment it's hard to tell for a user if a project is configured and what it currently does.
No worries if rows are not re-calculated.

**Comment by carolinux** [comment]
#5 is related - do we want to force sync from shapefile to the excel everytime we edit the configuration? Because otherwise the syncing is done only when we have edits to the shapefile layer.
So do we want the configuration to be editable or that I show a message telling the user to create a new project if they want to have a different master slave set up?

**Comment by m-kuhn** [comment]
I do not think that a configuration change should trigger a re-sync.

It should be possible
- to inspect the existing configuration (important)
- to change the expressions (not necessarily with forced update, the user will understand if it only affects future features)
- for changing layers etc a new project can be setup...

**Comment by carolinux** [comment]
I don't understand the third point. Do you mean setting up a new project using an existing one as  a template?

**Comment by m-kuhn** [comment]
It means, changing the layer and field is not a priority at all. If it is required to setup a new project for this, that's absolutely acceptable. Being able to change it is priority "nice-to-have".

**Comment by carolinux** [comment]
Ah, ok, got it. :)
Στις 4 Φεβ 2016 4:10 ΜΜ, ο χρήστης "Matthias Kuhn" notifications@github.com
έγραψε:

**Comment by carolinux** [comment]
now, changing the layers is greyed out when inspecting the settings

http://i.imgur.com/mrzewma.png
