### ISSUE TITLE
Python error on qgis startup

### ISSUE THREAD

**Issue by marcobra** [opengisch/shpsync#7]
Installed version: 0.6 (in /home/ubuntu/.qgis2/python/plugins/shpsync)
Available version: 0.6 (in QGIS Official Plugin Repository)

Hi i always get this error on starting qgis on ubuntu 

2016-02-12T09:47:25 1   Traceback (most recent call last):
              File "/home/ubuntu/.qgis2/python/plugins/shpsync/shpsync.py", line 115, in readSettings
                settings = Settings(settings_dict["excelName"], settings_dict["excelSheetName"], settings_dict["excelKeyName"],
            KeyError: 'excelName'

Thanks

**Comment by carolinux** [comment]
version 0.7 should fix it.
