### ISSUE TITLE
Plugin key error opening qgis existent project

### ISSUE THREAD

**Issue by marcobra** [opengisch/shpsync#8]
## On Ubuntu 15.10 Codename:   wily

with qgis  2.12.3-Lyon 

Plugin version: 0.7 (in /home/ubuntu/.qgis2/python/plugins/shpsync)

I get this error on opening existent projects:

![schermata del 2016-02-12 21-49-21](https://cloud.githubusercontent.com/assets/1607387/13020004/2c65d05c-d1d3-11e5-95b6-a6b5e270bcec.png)

Thank

**Comment by carolinux** [comment]
I am not sure how this particular project was set up, but generally if this is a project file that doesn't have shpsync activated, it should not be able to find anything in the settings (not an empty shpName, for instance in the settings_dict)

**Comment by carolinux** [comment]
At any case, I would edit the project file, find the part where it looks like this:

```
<SHPSYNC>
  <excelKeyName type="QString">ID</excelKeyName>
  <skipLines type="int">1</skipLines>
  <hideDialog type="int">1</hideDialog>
  <shpKeyName type="QString">id</shpKeyName>
  <excelSheetName type="QString">Tabelle1</excelSheetName>
  <shpName type="QString">empty_shapefile</shpName>
  <excelName type="QString">Tabelle1</excelName>
  <expressions type="QStringList">
    <value>FlaechePS2:::area($geometry)/10000</value>
  </expressions>
</SHPSYNC>
```

and make sure you have the line

```
  <skipLines type="int">1</skipLines>
```

**Comment by marcobra** [comment]
This error is not more showed with release 
0.8 (in /home/ubuntu/.qgis2/python/plugins/shpsync) of plugin

Thank

**Comment by carolinux** [comment]
OK, that's good!

**Comment by carolinux** [comment]
Note to self: I am still not sure how it happened that non existent string entries in the settings returned the default result for string ('') and somehow the ok was set to True in project_handler, via the function:

```
    prj.readEntry
```

**Comment by marcobra** [comment]
FYI in project file i have no settings/section
`<SHPSYNC> ...`

**Comment by carolinux** [comment]
Yes, the problem was something else.
